version: "3.9"

services:
  app-angular:
    image: "node:14.15.5"
    container_name: app-angular
    working_dir: /usr/www/app
    env_file:
      - .env
      - ../tt-app-angular/.env
    ports:
      - ${PORT:-4200}:${PORT:-4200}
    volumes:
      - "../tt-app-angular:/usr/www/app/"
    command: "/bin/sh  install.sh"
    networks:
      - app-fullstack

networks:
  app-fullstack:
